import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
    paddingTop: 60,
  },
  backButton: {
    position: 'absolute',
    top: 36,
    left: 20,
    zIndex: 10,
    flexDirection: 'row',
    backgroundColor: '#ffffffcc',
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  backText: {
    fontSize: 16,
    marginLeft: 8,
    color: '#1f2937',
    fontWeight: '600',
  },
  header: {
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 24,
    color: '#1f2937',
  },
  sectionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    marginBottom: 28,
  },
  dropZone: {
    width: width * 0.44,
    height: 260,
    backgroundColor: '#e0f7fa',
    borderColor: '#0ea5e9',
    borderWidth: 2,
    borderRadius: 22,
    alignItems: 'center',
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  dropZoneTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0284c7',
    marginBottom: 8,
  },
  innerDropZone: {
    flex: 1,
    width: '100%',
    backgroundColor: '#f0fdfd',
    borderRadius: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
    gap: 12,
  },
  resultMessage: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    color: '#d97706',
    marginVertical: 10,
  },
  explanationTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: 12,
    marginBottom: 6,
    color: '#334155',
  },
  examplesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginTop: 12,
  },
  imageWrapper: {
    width: 80,
    height: 80,
    margin: 10,
    borderRadius: 14,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: 64,
    height: 64,
    borderRadius: 10,
  },
  imageLabel: {
    fontSize: 12,
    color: '#475569',
    textAlign: 'center',
    marginTop: 6,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    width: '88%',
    maxHeight: '75%',
    padding: 22,
    backgroundColor: '#ffffffee',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 14,
    color: '#1f2937',
    textAlign: 'center',
  },
  modalText: {
    fontSize: 15,
    color: '#1e293b',
    marginBottom: 12,
    lineHeight: 22,
  },
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 28,
    marginTop: 36,
  },
  prevButton: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 180,
    height: 52,
    backgroundColor: '#e2e8f0',
    borderRadius: 26,
    paddingHorizontal: 16,
  },
  prevButtonCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#60a5fa',
    justifyContent: 'center',
    alignItems: 'center',
  },
  prevButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2563eb',
    marginLeft: 12,
  },
  nextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 180,
    height: 52,
    backgroundColor: '#3b82f6',
    borderRadius: 26,
    paddingHorizontal: 16,
  },
  nextButtonCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3b82f6',
    marginLeft: 12,
  },
});

export default styles;
